remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: "R for Information Studies"
description: "Introduction to R"

baseurl: /r-for-info-studies/
url: https://koshkov.github.io/

header_pages:
  - quickstart.md
